### PR TITLE
Attempt to port to Create 5.1

### PR DESCRIPTION
**Pull request by SiverDX**
* AllSection stuff was removed in https://github.com/Creators-of-Create/Create/commit/c4ffe8dabd6bde6deb20ebdfc027a7af5f6048cd - not sure what to do here
* Overloard resolution ambiguity in `Content.kt` for `REGISTRATE.blockEntity` - since I have no clue about Kotlin I'm not sure what to do here
* "Flywheel is now included in the Create jar (1.18)" - does this version need to be specifiec in `gradle.properties`?

### CODE REVIEW

**Comment by SiverDX** [comment]
I'll stop here but maybe it helps a bit

**Comment by SiverDX** [comment]
image

image

**Comment by zoi1op** [comment]
Nice

**Comment by PssbleTrngle** [comment]
Oh damn sorry I just saw this now after I started porting on my own, but thank you very much ❤️

**Comment by PssbleTrngle** [comment]
I'm not sure about the flywheel thing, previously it was still required  to include it manually because of forge shenanigans, but I'll try to remove it

**Comment by SiverDX** [comment]
Not needed anymore

**Pull request closed without merging**
